// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/4a8052290cc86a13f677cc25a5a9b82a64318b47/karma-jasmine/index.d.ts
declare function fdescribe(description: string, specDefinitions: () => void): void;
declare function fit(expectation: string, assertion: () => void): void;
